apiVersion: v1
kind: ConfigMap
metadata:
  name: go-rest-api-config
data:
  apiserver.toml: |-
    bind_addr = ":8443"
    database_url = "host=postgres dbname=postgres_production sslmode=disable user=postgres password=changeme"
    session_key = "idunnowhattowritehere"
