apiVersion: v1
kind: Service
metadata:
  name: go-rest-api
  labels:
    app: go-rest-api
spec:
  type: NodePort
  ports:
  - port: 3000
    targetPort: 8443
    nodePort: 30443
  selector:
   app: go-rest-api