apiVersion: v1
kind: Service
metadata:
  name: seq-ui
  labels:
    app: seq
spec:
  type: NodePort
  ports:
  # - port: 3000
  #   targetPort: 8443
  #   nodePort: 30443
  - port: 5341
    targetPort: 80
    # nodePort: 30002
  selector:
   app: seq
---
apiVersion: v1
kind: Service
metadata:
  name: seq
  labels:
    app: seq
spec:
  type: ClusterIP
  ports:
  - port: 5341
    targetPort: 5341
  selector:
   app: seq