apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgresql
  labels:
    app: postgres
spec:
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: postgres
  template:
    metadata:
      labels:
        app: postgres
        #tier: postgreSQL
    spec:
      containers:
        - image: postgres
          name: postgresql
          env:
            - name: POSTGRES_USER
              value: postgres
            - name: POSTGRES_DB
              value: postgres_production
            - name: POSTGRES_PASSWORD
              value: changeme
          ports:
            - containerPort: 5432
              name: postgresql
          volumeMounts:
            - name: postgresql
              mountPath: /var/lib/postgresql/data
          resources:
            limits:
              memory: "128Mi"
              cpu: "500m"
      volumes:
        - name: postgresql
          persistentVolumeClaim:
            claimName: postgres-claim