bind_addr = ":8080"
log_level = "debug"
database_url = "host=localhost dbname=restapi_dev sslmode=disable user=postgres password=changeme"
# postgresql://postgres:changeme@localhost/restapi_dev?sslmode=disable
session_key = "idunnowhattowritehere"